import React, { useState } from 'react';
import { 
  StyleSheet, 
  Text, 
  View, 
  SafeAreaView, 
  ScrollView, 
  TouchableOpacity, 
  Alert 
} from 'react-native';
import { COLORS, SPACING, TYPOGRAPHY, BORDER_RADIUS } from '../constants/theme';
import { TRANSLATIONS } from '../constants/translations';
import Card from '../components/Card';
import Button from '../components/Button';
import StatusPill from '../components/StatusPill';

export default function SettingsScreen() {
  const [lang, setLang] = useState<'en' | 'hi'>('en');
  const t = TRANSLATIONS[lang];

  // Configurable parameters (mocking slider state)
  const [matchThreshold, setMatchThreshold] = useState(0.72);
  const [livenessThreshold, setLivenessThreshold] = useState(0.85);
  const [isUpdatingModel, setIsUpdatingModel] = useState(false);

  const handleUpdateModel = () => {
    setIsUpdatingModel(true);
    // Simulate fetching new models from AWS S3
    setTimeout(() => {
      setIsUpdatingModel(false);
      Alert.alert(t.common.success, 'AI Models are up-to-date (v1.2.4-quantized).');
    }, 2000);
  };

  const handleWipeDatabase = () => {
    Alert.alert(
      'Wipe Encrypted Database?',
      'This will delete all local user profiles and sync logs. This action is irreversible.',
      [
        { text: t.common.cancel, style: 'cancel' },
        { 
          text: 'Wipe Clean', 
          style: 'destructive',
          onPress: () => Alert.alert(t.common.success, 'Secure SQLite database successfully wiped and re-encrypted.')
        }
      ]
    );
  };

  const changeThreshold = (type: 'match' | 'liveness', val: number) => {
    if (type === 'match') {
      setMatchThreshold(Number((matchThreshold + val).toFixed(2)));
    } else {
      setLivenessThreshold(Number((livenessThreshold + val).toFixed(2)));
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        
        {/* Language Selection */}
        <Text style={styles.sectionTitle}>{t.settings.langSelect}</Text>
        <Card style={styles.cardRow}>
          <TouchableOpacity 
            style={[styles.langBtn, lang === 'en' && styles.langBtnActive]}
            onPress={() => setLang('en')}
          >
            <Text style={[styles.langText, lang === 'en' && styles.langTextActive]}>English</Text>
          </TouchableOpacity>
          
          <TouchableOpacity 
            style={[styles.langBtn, lang === 'hi' && styles.langBtnActive]}
            onPress={() => setLang('hi')}
          >
            <Text style={[styles.langText, lang === 'hi' && styles.langTextActive]}>हिन्दी (Hindi)</Text>
          </TouchableOpacity>
        </Card>

        {/* Security Parameters */}
        <Text style={styles.sectionTitle}>Security Thresholds</Text>
        <Card>
          <View style={styles.thresholdHeader}>
            <Text style={styles.thresholdTitle}>{t.settings.thresholdLabel}</Text>
            <StatusPill label={String(matchThreshold)} type="info" />
          </View>
          <Text style={styles.thresholdDesc}>
            Higher values reduce False Acceptance Rate (FAR) but increase False Rejection Rate (FRR). Recommended: 0.72.
          </Text>
          <View style={styles.controlRow}>
            <TouchableOpacity style={styles.adjustBtn} onPress={() => changeThreshold('match', -0.05)}>
              <Text style={styles.adjustBtnText}>-0.05</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.adjustBtn} onPress={() => changeThreshold('match', 0.05)}>
              <Text style={styles.adjustBtnText}>+0.05</Text>
            </TouchableOpacity>
          </View>

          <View style={[styles.thresholdHeader, { marginTop: SPACING.md }]}>
            <Text style={styles.thresholdTitle}>{t.settings.livenessThresholdLabel}</Text>
            <StatusPill label={String(livenessThreshold)} type="warning" />
          </View>
          <Text style={styles.thresholdDesc}>
            Threshold score generated by MiniFASNet anti-spoofing checker. Recommended: 0.85.
          </Text>
          <View style={styles.controlRow}>
            <TouchableOpacity style={styles.adjustBtn} onPress={() => changeThreshold('liveness', -0.05)}>
              <Text style={styles.adjustBtnText}>-0.05</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.adjustBtn} onPress={() => changeThreshold('liveness', 0.05)}>
              <Text style={styles.adjustBtnText}>+0.05</Text>
            </TouchableOpacity>
          </View>
        </Card>

        {/* Maintenance Actions */}
        <Text style={styles.sectionTitle}>System Maintenance</Text>
        <Card>
          <Button 
            label={isUpdatingModel ? t.common.loading : t.settings.modelUpdateBtn}
            variant="outline"
            loading={isUpdatingModel}
            onPress={handleUpdateModel}
          />
          
          <Button 
            label={t.settings.clearDbBtn}
            variant="danger"
            onPress={handleWipeDatabase}
            style={styles.wipeBtn}
          />
        </Card>

        {/* Diagnostic Metadata */}
        <Card style={styles.diagCard}>
          <Text style={styles.diagTitle}>System Diagnostics</Text>
          <Text style={styles.diagText}>App Version: 0.0.1 (Alpha)</Text>
          <Text style={styles.diagText}>TFLite Runtime: C++ GPU Delegate</Text>
          <Text style={styles.diagText}>Local DB Store: SQLCipher SQLite v3</Text>
          <Text style={styles.diagText}>Device ID: UUID-8812-990-221A</Text>
        </Card>

      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    padding: SPACING.lg,
  },
  sectionTitle: {
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    fontSize: TYPOGRAPHY.fontSize.md,
    color: COLORS.textSecondary,
    marginTop: SPACING.md,
    marginBottom: SPACING.xs,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cardRow: {
    flexDirection: 'row',
    padding: 6,
  },
  langBtn: {
    flex: 1,
    height: 38,
    borderRadius: BORDER_RADIUS.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  langBtnActive: {
    backgroundColor: COLORS.primary,
  },
  langText: {
    fontFamily: TYPOGRAPHY.fontFamily.medium,
    fontSize: TYPOGRAPHY.fontSize.sm,
    color: COLORS.textSecondary,
  },
  langTextActive: {
    color: '#FFFFFF',
  },
  thresholdHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  thresholdTitle: {
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    fontSize: TYPOGRAPHY.fontSize.sm,
    color: COLORS.textPrimary,
  },
  thresholdDesc: {
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    fontSize: TYPOGRAPHY.fontSize.xs,
    color: COLORS.textSecondary,
    marginBottom: SPACING.sm,
    lineHeight: 16,
  },
  controlRow: {
    flexDirection: 'row',
    marginBottom: SPACING.sm,
  },
  adjustBtn: {
    backgroundColor: '#E9ECEF',
    paddingHorizontal: SPACING.md,
    paddingVertical: 6,
    borderRadius: BORDER_RADIUS.xs,
    marginRight: SPACING.sm,
  },
  adjustBtnText: {
    fontFamily: TYPOGRAPHY.fontFamily.medium,
    fontSize: TYPOGRAPHY.fontSize.xs,
    color: COLORS.textPrimary,
  },
  wipeBtn: {
    marginTop: SPACING.xs,
  },
  diagCard: {
    backgroundColor: '#EFEFEF',
    borderColor: '#CCCCCC',
    padding: SPACING.md,
  },
  diagTitle: {
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    fontSize: TYPOGRAPHY.fontSize.sm,
    color: COLORS.textPrimary,
    marginBottom: SPACING.xs,
  },
  diagText: {
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    fontSize: TYPOGRAPHY.fontSize.xs,
    color: COLORS.textSecondary,
    lineHeight: 18,
  },
});
